#!/usr/bin/env bash
# Configures unattended-upgrades to run a full weekly apt upgrade
# (all origins, not just security) with cleanup and an auto-reboot
# at a fixed off-hours time. Idempotent - safe to re-run.
#
# Usage:
#   sudo ./weekly-apt-updates-setup.sh
#
# Optional overrides (env vars):
#   UPGRADE_DAY=Sun        # systemd OnCalendar day-of-week
#   UPGRADE_TIME=02:30:00  # when the weekly upgrade run starts
#   REBOOT_TIME=03:30      # when to reboot afterward, if required
#
# Example for a different schedule:
#   sudo UPGRADE_DAY=Sat UPGRADE_TIME=01:00:00 REBOOT_TIME=02:00 ./weekly-apt-updates-setup.sh

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

UPGRADE_DAY="${UPGRADE_DAY:-Sun}"
UPGRADE_TIME="${UPGRADE_TIME:-02:30:00}"
REBOOT_TIME="${REBOOT_TIME:-03:30}"
CONF=/etc/apt/apt.conf.d/50unattended-upgrades

echo "==> Installing unattended-upgrades (no-op if already installed)"
apt-get update -qq
apt-get install -y unattended-upgrades update-notifier-common

echo "==> Writing /etc/apt/apt.conf.d/20auto-upgrades"
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF

echo "==> Patching $CONF"
[[ -f "${CONF}.orig" ]] || cp "$CONF" "${CONF}.orig"

# Enable the regular "-updates" pocket (not just security) inside Allowed-Origins.
if grep -qE '^\s*"\$\{distro_id\}:\$\{distro_codename\}-updates";' "$CONF"; then
  :
elif grep -qE '^//\s*"\$\{distro_id\}:\$\{distro_codename\}-updates";' "$CONF"; then
  sed -i -E 's#^//(\s*"\$\{distro_id\}:\$\{distro_codename\}-updates";)#\1#' "$CONF"
else
  sed -i '/^Unattended-Upgrade::Allowed-Origins {/a\	"${distro_id}:${distro_codename}-updates";' "$CONF"
fi

set_uu_option() {
  local key="$1" value="$2"
  if grep -qE "^[[:space:]]*Unattended-Upgrade::${key}[[:space:]]" "$CONF"; then
    sed -i -E "s#^[[:space:]]*Unattended-Upgrade::${key}[[:space:]]+\"[^\"]*\";#Unattended-Upgrade::${key} \"${value}\";#" "$CONF"
  elif grep -qE "^//[[:space:]]*Unattended-Upgrade::${key}[[:space:]]" "$CONF"; then
    sed -i -E "s#^//[[:space:]]*Unattended-Upgrade::${key}[[:space:]]+\"[^\"]*\";#Unattended-Upgrade::${key} \"${value}\";#" "$CONF"
  else
    printf '\nUnattended-Upgrade::%s "%s";\n' "$key" "$value" >> "$CONF"
  fi
}

set_uu_option "Remove-Unused-Dependencies" "true"
set_uu_option "Remove-Unused-Kernel-Packages" "true"
set_uu_option "Automatic-Reboot" "true"
set_uu_option "Automatic-Reboot-WithUsers" "true"
set_uu_option "Automatic-Reboot-Time" "$REBOOT_TIME"

echo "==> Overriding apt-daily-upgrade.timer to run weekly (${UPGRADE_DAY} ${UPGRADE_TIME})"
mkdir -p /etc/systemd/system/apt-daily-upgrade.timer.d
cat > /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf <<EOF
[Timer]
OnCalendar=
OnCalendar=${UPGRADE_DAY} *-*-* ${UPGRADE_TIME}
RandomizedDelaySec=0
Persistent=false
EOF

systemctl daemon-reload
systemctl restart apt-daily-upgrade.timer

# Human-readable schedule for the banner: "Sat,Sun" -> "Saturday, Sunday",
# "Mon..Fri" -> "Monday-Friday", "02:30:00" -> "02:30".
SCHED_DAYS=$(echo "$UPGRADE_DAY" | sed -e 's/\bMon\b/Monday/g; s/\bTue\b/Tuesday/g; s/\bWed\b/Wednesday/g' \
  -e 's/\bThu\b/Thursday/g; s/\bFri\b/Friday/g; s/\bSat\b/Saturday/g; s/\bSun\b/Sunday/g' \
  -e 's/\.\./-/g; s/,/, /g')
SCHED_TIME=$(echo "$UPGRADE_TIME" | sed 's/^\([0-9]*:[0-9]*\):00$/\1/')

echo "==> Installing login banner (schedule + last update/reboot/next update table) at /etc/update-motd.d/96-weekly-apt-status"
cat > /etc/update-motd.d/96-weekly-apt-status <<EOF
#!/bin/sh
# Shows the weekly update schedule and a table of the latest update (and its
# result), the last reboot and the next scheduled update, so an admin logging
# in can tell whether the scheduled update/reboot actually happened.
# Generated by weekly-apt-updates-setup.sh - re-run it to change the schedule.
SCHED_DAYS="$SCHED_DAYS"
SCHED_TIME="$SCHED_TIME"
REBOOT_TIME="$REBOOT_TIME"
EOF
cat >> /etc/update-motd.d/96-weekly-apt-status <<'EOF'
SVC=apt-daily-upgrade.service
TIMER=apt-daily-upgrade.timer
TZNAME=$(date +%Z)

# Normalize a systemd/uptime timestamp to "Sun 2026-10-04 02:30 CDT".
fmt() { date -d "$1" '+%a %Y-%m-%d %H:%M %Z' 2>/dev/null || echo "$1"; }

# Latest system update: end of the last apt-daily-upgrade.service run.
LAST=$(systemctl show "$SVC" -p ExecMainExitTimestamp --value 2>/dev/null)
CODE=$(systemctl show "$SVC" -p ExecMainStatus --value 2>/dev/null)
if [ -n "$LAST" ] && [ "$LAST" != "n/a" ]; then
    LAST_WHEN=$(fmt "$LAST")
    if [ "$CODE" = "0" ]; then LAST_STATUS="OK"; else LAST_STATUS="FAILED (exit $CODE)"; fi
else
    LAST_WHEN="never"; LAST_STATUS="-"
fi

# Last system reboot (uptime -s; wtmp/`last reboot` can be stale).
BOOT=$(uptime -s 2>/dev/null)
BOOT_WHEN=$(fmt "$BOOT")
if [ -f /var/run/reboot-required ]; then
    BOOT_STATUS="REBOOT PENDING"
else
    BOOT_STATUS=$(uptime -p 2>/dev/null | cut -d, -f1-2)
fi

# Next scheduled update, straight from the timer.
NEXT=$(systemctl show "$TIMER" -p NextElapseUSecRealtime --value 2>/dev/null)
NEXT_EPOCH=""
case "$NEXT" in
    ""|n/a) ;;  # empty would make `date -d` return midnight today
    *) NEXT_EPOCH=$(date -d "$NEXT" +%s 2>/dev/null) ;;
esac
if [ -n "$NEXT_EPOCH" ]; then
    NEXT_WHEN=$(fmt "$NEXT")
    SECS=$((NEXT_EPOCH - $(date +%s)))
    if   [ "$SECS" -ge 86400 ]; then N=$((SECS / 86400)); U=day
    elif [ "$SECS" -ge 3600 ];  then N=$((SECS / 3600));  U=hour
    elif [ "$SECS" -ge 60 ];    then N=$((SECS / 60));    U=minute
    else N=""; fi
    if [ -n "$N" ]; then
        [ "$N" -eq 1 ] || U="${U}s"
        NEXT_STATUS="in $N $U"
    else
        NEXT_STATUS="due now"
    fi
else
    NEXT_WHEN="not scheduled"; NEXT_STATUS="check: systemctl status $TIMER"
fi

echo "Weekly system updates run every $SCHED_DAYS at $SCHED_TIME $TZNAME;"
echo "if an update requires it, the system reboots at $REBOOT_TIME $TZNAME."
echo
printf '%s\t%s\t%s\n' \
    "Event" "When" "Status" \
    "Latest system update" "$LAST_WHEN" "$LAST_STATUS" \
    "Last system reboot" "$BOOT_WHEN" "$BOOT_STATUS" \
    "Next scheduled update" "$NEXT_WHEN" "$NEXT_STATUS" |
awk -F'\t' '
    { for (i = 1; i <= NF; i++) { cell[NR, i] = $i; if (length($i) > w[i]) w[i] = length($i) } }
    END {
        rule = "  +"; for (i = 1; i <= 3; i++) { s = ""; for (j = 0; j < w[i] + 2; j++) s = s "-"; rule = rule s "+" }
        print rule
        for (r = 1; r <= NR; r++) {
            line = "  |"; for (i = 1; i <= 3; i++) line = line sprintf(" %-" w[i] "s |", cell[r, i])
            print line
            if (r == 1) print rule
        }
        print rule
    }'

case "$LAST_STATUS" in
    FAILED*) echo "  Last update failed - check: sudo journalctl -u $SVC" ;;
esac
EOF
chmod 755 /etc/update-motd.d/96-weekly-apt-status
chown root:root /etc/update-motd.d/96-weekly-apt-status

echo "==> Done. Next scheduled run:"
systemctl list-timers apt-daily-upgrade.timer --all --no-pager

echo
echo "==> Sanity check (dry run, changes nothing):"
unattended-upgrade --dry-run --debug 2>&1 | tail -40

echo
echo "Setup complete. Logs will appear in /var/log/unattended-upgrades/ after the first real run."
